services:
  prefect-server:
    image: prefecthq/prefect:2-python3.10
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER__TELEMETRY__ENABLED=false
    command: prefect server start
    networks:
      - internal
  prefect-deployments:
    restart: always
    build:
      context: ./deployments
      dockerfile: Dockerfile
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_SERVER__TELEMETRY__ENABLED=false
      - PREFECT_SERVER_API_HOST=0.0.0.0
    depends_on:
      - prefect-server
    networks:
      - internal
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - "80:80"
    networks:
      - internal
  oauth2-proxy:
    image: bitnami/oauth2-proxy:7.6.0
    environment:
      - OAUTH2_PROXY_PROVIDER=google
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=cow.fi
      - OAUTH2_PROXY_HTTP_ADDRESS=http//0.0.0.0:4180
      - OAUTH2_PROXY_REDIRECT_URL=${OAUTH2_PROXY_REDIRECT_URL}
      - OAUTH2_PROXY_UPSTREAMS=http://prefect-server:4200
    networks:
      - internal
    
networks:
  internal:
    driver: bridge
