apiVersion: v1
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location /oauth2/ {
          proxy_pass http://oauth2-proxy:4180;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
          auth_request /oauth2/auth;
          error_page 401 = /oauth2/sign_in;

          proxy_pass http://prefect-server:4200;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  name: nginx-cm0
