apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: oauth2-proxy
  template:
    metadata:
      labels:
        service: oauth2-proxy
    spec:
      containers:
        - env:
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: cow.fi
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: http//0.0.0.0:4180
            - name: OAUTH2_PROXY_PROVIDER
              value: google
            - name: OAUTH2_PROXY_UPSTREAMS
              value: http://prefect-server:4200
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: OAUTH2_PROXY_CLIENT_ID
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: OAUTH2_PROXY_CLIENT_SECRET
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: OAUTH2_PROXY_COOKIE_SECRET
            - name: OAUTH2_PROXY_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: OAUTH2_PROXY_REDIRECT_URL
          image: bitnami/oauth2-proxy:7.6.0
          name: oauth2-proxy
      restartPolicy: Always
