apiVersion: v1
kind: Service
metadata:
  labels:
    service: prefect-server
  name: prefect-server
spec:
  ports:
    - name: "4200"
      port: 4200
      targetPort: 4200
  selector:
    service: prefect-server
