name: deploy

on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.licenses=MIT OR Apache-2.0
      - name: Push Project Image
        uses: docker/build-push-action@v3
        with:
          context: ./deployments
          file: ./deployments/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            ${{ secrets.OAUTH2_PROXY_CLIENT_ID }}
            ${{ secrets.OAUTH2_PROXY_CLIENT_SECRET }}
            ${{ secrets.OAUTH2_PROXY_COOKIE_SECRET }}
            ${{ secrets.OAUTH2_PROXY_REDIRECT_URL }}
